### ISSUE TITLE
no issue here

### ISSUE THREAD

**Issue by JeffreySarnoff** [fcard/SelfFunctions.jl#14]
@fcard @marius311 
( listening to this :cool: :musical_note:  )

_here is the same complement, using more words_
>   
           I found your work reaching fields through their own type's surface refreshing.  
           I learned something new about using macros from code you each posted.  
           This design "sounds cool".

**Comment by fcard** [comment]
Oh, I forgot about this! Hehe. I will close as resolved, since there is "no issue here". (Is this a pipe thing?)

Github issues aren't meant to be used like this but I will take 'em where I can get 'em, so thank you and have a good day (many months later).

Next time feel free to send an e-mail or something.
